### ISSUE TITLE
Data returned by `chr_uzemi()` seems to be out of date

### ISSUE THREAD

**Issue by petrbouchal** [jlacko/RCzechia#18]
Compare to output from `{CzechData}` i.e. direct from CUZK datasets

```
chu_rcz <- RCzechia::chr_uzemi() #preprocessed data
chu_cd <- CzechData::load_Data50("ChraneneUzemi") # direct from CUZK
setdiff(chu_cd$NAZEV, chu_rcz$NAZEV)
```

One is an obsolete name, another is a newly created protected area (2016).

I have not checked but suspect this may also be the case for other datasets served by `{RCzechia}`?

**Comment by jlacko** [comment]
Thanks for the pointer @petrbouchal !

The admin areas (obce, kraje, okresy...) are based on RUIAN since 1.5.0 and are current as of 2020-03-31; these should be OK.

The rest - like chráněné území - come from the original ARC ČR 500 (https://www.arcdata.cz/produkty/geograficka-data/arccr-500) and are current as of October 2016 (i.e. getting somewhat stale by now).

I will check & correct the chráněná území dataset, and think hard about the road network. Rivers are not going anywhere and there is not much happening on železnice, but silnice seem to be the most volatile object of the old ARC ČR lot.

**Comment by jlacko** [comment]
Chráněná území are now based on AOPK Open Data - https://data.nature.cz/ - rather than the old ARC ČR 500.

Data are current to September 2020 and can be easily updated by running `/data-raw/digest-chr-uzemi.R` (based on a current shapefile from AOPK).

As an extra bonus maloplošná území are also included.

**Comment by jlacko** [comment]
To verify the original bug:
```
chu_rcz <- subset(readRDS(url("https://rczechia.jla-data.net/ChrUzemiAOPK.rds")), PLOCHA = "velkoplošná")
chu_cd <- CzechData::load_Data50("ChraneneUzemi") # direct from CUZK
setdiff(chu_cd$NAZEV, chu_rcz$NAZEV)
```
returns expected zero difference
