### ISSUE TITLE
Data download times: JOSS Review

### ISSUE THREAD

**Issue by nickbearman** [jlacko/RCzechia#58]
A small comment. When pulling in various data sets, some of them are bigger than others. Is it possible to add some type of progress measure, particularly for the bigger data sets?

e.g. when I ran `relief <- vyskopis("actual", cropped = TRUE)`

it said `RCzechia: downloading remote dataset.`

and then just sat there until it had finished. Fortunately it didn't take too long, but if a new user didn't know this they might think something had gone wrong. 

https://github.com/openjournals/joss-reviews/issues/5082

**Comment by jlacko** [comment]
Thank you  @nickbearman for the fresh look; I fully agree with your observation.

A progress bar will be reported with each download. I just need to make sure that it does not end up in vignette or some other place where it does not belong.

**Comment by nickbearman** [comment]
Wonderful - this works really well. 

Now, when I run:
`relief <- vyskopis("actual", cropped = TRUE)`
I get
`RCzechia: downloading remote dataset.`
and a progress update:
`[50%] Downloaded 72192398 bytes...`

Am guessing this is currently in the DEV version and will propagate to the CRAN version in due course. 

Happy for you to close this if you are happy too.

**Comment by jlacko** [comment]
Thanks for the kind words! I am keeping the issue open because my code had been set to quiet download mode (actively suppressing the progress bar) earlier in the development of the package. I had turned it to "loud" mode = progress is reported, but I no longer remember exactly why it was quiet - so I keep the issue intentionally open to do more tests. Most likely there will be no impact but I like GitHub to remind me to make doubly sure before next CRAN submission (which I plan to make when the review process concludes, in case there will be more changes).
